use colonialadventuretours;

select RESERVATIN_ID,TRIP_ID, CUSTOMER_NUM, CUSTOMER_LASTNAME
from reservation
WHERE CUSTEOMER_LASTNAME;

SELECT RESERVATION_ID, TRIP_ID, NUM_PERSONS
FROM reservation
WHERE CUSTOMER_FIRSTNAME = "Ryan" && CUSTOMER_LASTNAME = "gOFF";

select TRIP_NAME
FROM trip
where GUIDE_NAME = "Miles Abrams";


select LAST_NAME, FIRST_NAME
FROM GUIDE
WHERE GUIDE_NUM
IN (
	SELECT DISTINCT GUIDE_NUM FROM TRIP GUUDES TG WHERE TO . 
    TRIP_ID in
		(
		  SELECT T.TRIP_ID FROM THIS T WHEERE T.TYPE = 'ADDLING'
          )
	);
    
    SELECT G.LASTNAE G.FIRST_NAME
    FROM GUIDE G, TRIP T
    INNER JOIN T, G WEHRE T.TYPE = 'PADDLING';
    
    SELECT T1.TRIP_ID, T1.TRIP_NAME, T2.TRIP_ID, T2.TRIP+name_const()
    FROM TRIP T1, TRIP T2
    WHERE T1.START_LOCATION = 'WEATHERSFIELD'
    AND T2.START_LOCATION = 'WEATHERSFIELDS'
    ORDER BY T1.TRIP_ID, T2.TRIP_ID;
    
    SELECT T.TRIP_NAME
    FROM TRP trip
    INNER JOIN reservation R ON T.TRIP_ID = R.TRIP_ID
    WHERE t.TRIP = 'MIKING'
    ORDER BY T.TRIP_NAME;
    