use colonialadventuretours;

#Part 1

CREATE TABLE PADDLING
(
Trip_ID Dedcimal(3,0) PRIMARY KEY NOT NULL,
Trip_Name CHAR(75),
State CHAR(2),
Distance DEC(4,0),
Max_GRP_Size DEC(4,0),
Season CHAR(20)
);
#part 2
INSERT INTO PADDLING
SELECT Trip_ID, Trip_Name, State, Distance, Max_GRP_Size, Season
FROM trip
WHERE TYPE = "PADDLING";
#Part 3
UPDATE trip
set MAX_GRP_SIZE = MAX_GRP_SIZE + 2
WHERE STATE = "CT";
UPDATE PADDLING
set MAX_GRP_SIZE = MAX_GRP_SIZE + 2
WHERE STATE = "CT";

#PART 4
INSERT INTO PADDLING
VALUES
(43, "Lake Champlain Tour", "VT", 12, 16, "Summer");

#part 5

DELETe FROm PADDLING
WHERE TRIP_ID = 23;

#PART 6
ALTER TABLE PADDLING
MODIFY DISTANCE DEC(4, 0) NOT NULL;
#PART 7
ALTER TABLE PADDLING
ADD DIFFICULTY_LEVEL CHAR(3) DEFAULT "MOD";

#Part 8

UPDATE PADDLING
SET DIFFICULTY_LEVEL = "HRD"
WHERE TRIP_NAME = "Lake Champlain Tour";

#part9

ALTER TABLE PADDLING
MODIFY SEASON CHAR(25);
#PART 10
ALTER TABLE PADDLING
MODIFY DIFFICULTY_LEVEL CHAR(3) NULL;

#Part 11
DROP TABLE PADDLING; 